import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import { RefreshCw, Save, Smartphone } from "lucide-react";
import { toast } from "react-toastify";

const inputClass="w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-100";
const money=minor=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(Number(minor||0)/100);
const statusClass={successful:"bg-emerald-50 text-emerald-700",pending:"bg-amber-50 text-amber-700",refunded:"bg-blue-50 text-blue-700",failed:"bg-red-50 text-red-700"};

export default function AirtimeManagement(){
 const [settings,setSettings]=useState(null),[form,setForm]=useState(null),[summary,setSummary]=useState({}),[rows,setRows]=useState([]),[pagination,setPagination]=useState({page:1,limit:20,total:0}),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const {data}=await axios.get(`/admin/coins/airtime?page=${pagination.page}&limit=${pagination.limit}&status=${status}&search=${encodeURIComponent(search)}`);setSettings(data.settings);setForm(current=>current||{pointsPerNaira:data.settings.points_per_naira,minimumAmount:Number(data.settings.minimum_amount_minor)/100,maximumAmount:Number(data.settings.maximum_amount_minor)/100,isEnabled:data.settings.is_enabled});setSummary(data.summary||{});setRows(data.redemptions||[]);setPagination(x=>({...x,...data.pagination}))}catch(e){toast.error(e.response?.data?.message||"Unable to load airtime redemptions.")}finally{setLoading(false)}},[pagination.page,pagination.limit,search,status]);
 useEffect(()=>{const timer=setTimeout(load,search?300:0);return()=>clearTimeout(timer)},[load,search]);
 const save=async e=>{e.preventDefault();setSaving(true);try{const {data}=await axios.put("/admin/coins/airtime/settings",{...form,pointsPerNaira:Number(form.pointsPerNaira),minimumAmount:Number(form.minimumAmount),maximumAmount:Number(form.maximumAmount)});setSettings(data.settings);setForm({pointsPerNaira:data.settings.points_per_naira,minimumAmount:Number(data.settings.minimum_amount_minor)/100,maximumAmount:Number(data.settings.maximum_amount_minor)/100,isEnabled:data.settings.is_enabled});toast.success("Airtime conversion settings saved.")}catch(e){toast.error(e.response?.data?.message||e.response?.data?.errors?.[0]?.message||"Unable to save settings.")}finally{setSaving(false)}};
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><Smartphone className="text-purple-600"/>Airtime redemptions</h1><p className="mt-1 text-sm text-slate-500">Control the points-to-airtime rate and audit every player redemption.</p></div><button onClick={load} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-semibold"><RefreshCw size={16}/>Refresh</button></header>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["All requests",summary.total||0],["Successful",summary.successful||0],["Airtime delivered",money(summary.amount_minor)],["Points converted",Number(summary.points_used||0).toLocaleString()]].map(([label,value])=><article key={label} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value}</p></article>)}</div>
 {form&&<form onSubmit={save} className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">Conversion settings</h2><p className="text-sm text-slate-500">The rate used at purchase time is permanently stored on each record.</p></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isEnabled} onChange={e=>setForm(x=>({...x,isEnabled:e.target.checked}))}/>Allow redemptions</label></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Points for NGN 1<input required type="number" min="1" value={form.pointsPerNaira} onChange={e=>setForm(x=>({...x,pointsPerNaira:e.target.value}))} className={`mt-1 ${inputClass}`}/></label><label className="text-sm font-semibold">Minimum airtime (NGN)<input required type="number" min="1" value={form.minimumAmount} onChange={e=>setForm(x=>({...x,minimumAmount:e.target.value}))} className={`mt-1 ${inputClass}`}/></label><label className="text-sm font-semibold">Maximum airtime (NGN)<input required type="number" min="1" value={form.maximumAmount} onChange={e=>setForm(x=>({...x,maximumAmount:e.target.value}))} className={`mt-1 ${inputClass}`}/></label></div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-slate-400">Example: NGN 100 costs {(Number(form.pointsPerNaira||0)*100).toLocaleString()} points.</p><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-purple-600 px-5 py-2.5 font-bold text-white disabled:opacity-60"><Save size={16}/>{saving?"Saving...":"Save settings"}</button></div></form>}
 <section className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap gap-3"><input value={search} onChange={e=>{setSearch(e.target.value);setPagination(x=>({...x,page:1}))}} placeholder="Search player, phone or reference" className={`${inputClass} max-w-md`}/><select value={status} onChange={e=>{setStatus(e.target.value);setPagination(x=>({...x,page:1}))}} className={`${inputClass} max-w-48`}><option value="">All statuses</option><option value="successful">Successful</option><option value="pending">Pending</option><option value="refunded">Refunded</option><option value="failed">Failed</option></select></div>{loading?<div className="py-20 text-center text-slate-400">Loading airtime history...</div>:rows.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Player</th><th className="p-3">Recipient</th><th className="p-3">Value</th><th className="p-3">Points / rate</th><th className="p-3">Status</th><th className="p-3">References</th><th className="p-3">Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b align-top last:border-0"><td className="p-3"><b>{r.user_name}</b><p className="text-xs text-slate-400">{r.user_email}</p></td><td className="p-3"><b>{r.phone}</b><p className="text-xs text-slate-400">{r.network}</p></td><td className="p-3 font-bold">{money(r.amount_minor)}</td><td className="p-3">{Number(r.points_used).toLocaleString()}<p className="text-xs text-slate-400">{r.points_per_naira}/NGN</p></td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusClass[r.status]||"bg-slate-100"}`}>{r.status}</span>{r.failure_reason&&<p className="mt-2 max-w-xs text-xs text-red-500">{r.failure_reason}</p>}</td><td className="p-3 text-xs"><p className="max-w-xs break-all">{r.reference}</p>{r.provider_reference&&<p className="mt-1 text-slate-400">Provider: {r.provider_reference}</p>}</td><td className="whitespace-nowrap p-3 text-slate-500">{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="py-20 text-center text-slate-400">No matching airtime redemptions.</div>}<div className="mt-5 flex items-center justify-between text-sm text-slate-500"><span>{Number(pagination.total||0).toLocaleString()} records</span><div className="flex gap-2"><button disabled={pagination.page<=1} onClick={()=>setPagination(x=>({...x,page:x.page-1}))} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={pagination.page*pagination.limit>=pagination.total} onClick={()=>setPagination(x=>({...x,page:x.page+1}))} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div></section>
 {settings?.updated_at&&<p className="mt-3 text-right text-xs text-slate-400">Settings last updated {new Date(settings.updated_at).toLocaleString()}</p>}</div></main>;
}
