import React,{useCallback,useEffect,useState}from"react";import axios from"axios";import{Eye,Pencil,Plus,Trash2}from"lucide-react";import{useNavigate,useSearchParams}from"react-router-dom";import{toast}from"react-toastify";
import PageNavigation from"../../components/page-navigation";import ConfirmDialog from"../../components/confirm-dialog";import FormDialog from"../../components/form-dialog";
import ImageUploadField from"../../components/image-upload-field";import{removeCatalogImage,uploadCatalogImage}from"../../data/media";
const blank={name:"",description:"",imageUrl:""},field="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-purple-500 focus:ring-4 focus:ring-purple-100";
export default function GamesCategories(){const nav=useNavigate(),[params]=useSearchParams(),ageId=params.get("ageGroup"),[age,setAge]=useState(null),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[form,setForm]=useState(blank),[imageFile,setImageFile]=useState(null),[editing,setEditing]=useState(null),[dialog,setDialog]=useState(false),[deleting,setDeleting]=useState(null),[busy,setBusy]=useState(false);
const load=useCallback(async()=>{if(!ageId)return;setLoading(true);try{const[g,c]=await Promise.all([axios.get("/admin/catalog/age-groups"),axios.get(`/admin/catalog/age-groups/${ageId}/categories`)]);setAge(g.data.ageGroups.find(x=>x.id===ageId));setItems(c.data.categories||[])}catch(e){toast.error("Unable to load categories")}finally{setLoading(false)}},[ageId]);useEffect(()=>{load()},[load]);
const open=(item=null)=>{setEditing(item);setForm(item?{name:item.name,description:item.description||"",imageUrl:item.image_url||""}:blank);setImageFile(null);setDialog(true)};
const save=async e=>{e.preventDefault();setBusy(true);let uploaded="";try{uploaded=imageFile?await uploadCatalogImage(imageFile):"";const payload={...form,imageUrl:uploaded||form.imageUrl,ageGroupId:ageId};editing?await axios.put(`/admin/catalog/categories/${editing.id}`,payload):await axios.post("/admin/catalog/categories",payload);if(uploaded&&form.imageUrl)await removeCatalogImage(form.imageUrl).catch(()=>{});toast.success(`Category ${editing?"updated":"created"}`);setDialog(false);load()}catch(x){if(uploaded)await removeCatalogImage(uploaded).catch(()=>{});toast.error(x.response?.data?.message||x.response?.data?.errors?.[0]?.message||"Unable to save category")}finally{setBusy(false)}};
const remove=async()=>{setBusy(true);try{await axios.delete(`/admin/catalog/categories/${deleting.id}`);toast.success("Category deleted");setDeleting(null);load()}catch(e){toast.error(e.response?.data?.message||"Unable to delete category")}finally{setBusy(false)}};
if(!ageId)return <div className="p-8">Select an age group first.</div>;return <div className="mx-auto w-full max-w-7xl px-6 pb-10"><PageNavigation items={[{label:"Age Groups",to:"/categories"},{label:age?.name||"Categories"}]} title={`${age?.name||"Age group"} Categories`} description={`Create subjects and learning categories for ages ${age?.min_age||""}–${age?.max_age||""}.`} action={<button onClick={()=>open()} className="flex items-center gap-2 rounded-xl bg-purple-600 px-5 py-3 text-sm font-bold text-white"><Plus size={18}/>Add Category</button>}/>
{loading?<div className="rounded-2xl bg-white p-16 text-center text-slate-400">Loading categories...</div>:items.length?<div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><table className="w-full text-left"><thead className="bg-slate-50 text-sm text-slate-500"><tr><th className="px-6 py-4">Category</th><th className="px-6 py-4">Description</th><th className="px-6 py-4">Levels</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{items.map(x=><tr key={x.id}><td className="px-6 py-5 font-bold text-slate-900">{x.name}</td><td className="max-w-xl px-6 py-5 text-sm text-slate-600">{x.description||"No description"}</td><td className="px-6 py-5"><span className="rounded-full bg-purple-50 px-3 py-1 text-xs font-semibold text-purple-700">{x.level_count} levels</span></td><td className="px-6 py-5"><div className="flex justify-end gap-3"><button onClick={()=>nav(`/categories/view-categories?ageGroup=${ageId}&category=${x.id}`)} className="flex items-center gap-1 text-sm font-semibold text-slate-600"><Eye size={15}/>View</button><button onClick={()=>open(x)} className="flex items-center gap-1 text-sm font-semibold text-purple-600"><Pencil size={15}/>Edit</button><button onClick={()=>setDeleting(x)} className="flex items-center gap-1 text-sm font-semibold text-red-500"><Trash2 size={15}/>Delete</button></div></td></tr>)}</tbody></table></div>:<div className="rounded-2xl border-2 border-dashed bg-white p-16 text-center"><h2 className="text-lg font-bold">No categories yet</h2><p className="mt-2 text-sm text-slate-500">Create the first category under this age group.</p><button onClick={()=>open()} className="mt-5 rounded-xl bg-purple-600 px-5 py-3 font-semibold text-white">Add Category</button></div>}
<FormDialog open={dialog} title={editing?"Edit category":"Create category"} onClose={()=>setDialog(false)}><form onSubmit={save} className="space-y-5"><label className="block text-sm font-semibold">Category name<input required className={`${field} mt-2`} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Mathematics"/></label><label className="block text-sm font-semibold">Description<textarea required rows="4" className={`${field} mt-2 resize-none`} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><ImageUploadField file={imageFile} currentUrl={form.imageUrl} onChange={setImageFile}/><div className="flex justify-end gap-3"><button type="button" onClick={()=>setDialog(false)} className="rounded-xl border px-5 py-3 font-semibold">Cancel</button><button disabled={busy} className="rounded-xl bg-purple-600 px-6 py-3 font-semibold text-white">{busy?"Uploading and saving...":"Save category"}</button></div></form></FormDialog>
<ConfirmDialog open={!!deleting} loading={busy} onCancel={()=>setDeleting(null)} onConfirm={remove} title="Delete category?" message={`Deleting ${deleting?.name||"this category"} will also permanently remove every level under it.`}/></div>}
